Merge harvest-legacy, registry-pds3-catalog, and registry-mgr-legacy
NASA-PDS/registry-harvest-legacy pull request #80
Opened 2024-07-21 17:50 UTC by jordanpadams

## 🗒️ Summary
Merge all repos together and refactor our search-core into separate library

## ⚙️ Test Data and/or Report
```
[SUCCESS] Harvest Successful
[INFO] Check solr docs match expected
[SUCCESS] Solr Doc Diff Successful
[INFO] Registry Manager Load
curl -X POST -H Content-Type: text/xml -d @/Users/jpadams/registry-data//solr-docs/solr-docs/solr_doc_0.xml http://localhost:8983/solr/data/update/xslt?commit=true&tr=add-hierarchy.xsl
<?xml version="1.0" encoding="UTF-8"?>
<response>

<lst name="responseHeader">
  <int name="rf">1</int>
  <int name="status">0</int>
  <int name="QTime">391</int>
</lst>
</response>
[SUCCESS] Registry Manager Load Successful
```

## ♻️ Related Issues

Resolves #77

2024-07-22 16:28 UTC, nutjob4life requested changes
- The conflict markers left in the codeql YAML should definitely be addressed
- There's _lots_ of commented-out code that should just be deleted completely (or have additional comments saying why), but I'll leave that as an option to consider

This pull request is so big it actually made Chrome unusable! I could count multiple seconds for keystrokes to appear in review fields

Safari on macOS handled it better than Chrome, but it too was lethargic. However Firefox was the clear winner! It had no issues. I think I just found my new preferred "work browser"

2024-07-22 17:48 UTC, jordanpadams commented on .github/workflows/codeql-analysis.yml
> +<<<<<<< HEAD
Fixed per https://github.com/NASA-PDS/registry-harvest-legacy/pull/80/commits/1bc79add5c802ac1c8f463b84a41b7ae4e2048af

2024-07-22 17:51 UTC, jordanpadams commented on catalog-legacy/src/main/java/gov/nasa/pds/citool/comparator/CatalogComparator.java
> +/*
resolved per https://github.com/NASA-PDS/registry-harvest-legacy/pull/80/commits/438ebcb33d20ceb8fc3cc5f3fc29912d58a13748

2024-07-22 17:51 UTC, jordanpadams commented on catalog-legacy/src/main/java/gov/nasa/pds/citool/CIToolComparator.java
> +/*
resolved per https://github.com/NASA-PDS/registry-harvest-legacy/pull/80/commits/438ebcb33d20ceb8fc3cc5f3fc29912d58a13748

2024-07-22 17:51 UTC, jordanpadams commented on catalog-legacy/src/main/java/gov/nasa/pds/citool/comparator/CatalogComparator.java
> +/*
resolved per https://github.com/NASA-PDS/registry-harvest-legacy/pull/80/commits/438ebcb33d20ceb8fc3cc5f3fc29912d58a13748

2024-07-22 17:51 UTC, jordanpadams commented on catalog-legacy/src/main/java/gov/nasa/pds/citool/comparator/CatalogComparator.java
> +/*
resolved per https://github.com/NASA-PDS/registry-harvest-legacy/pull/80/commits/438ebcb33d20ceb8fc3cc5f3fc29912d58a13748

2024-07-22 17:51 UTC, jordanpadams commented on catalog-legacy/src/main/java/gov/nasa/pds/citool/comparator/CatalogComparator.java
> +/*
resolved per https://github.com/NASA-PDS/registry-harvest-legacy/pull/80/commits/438ebcb33d20ceb8fc3cc5f3fc29912d58a13748

2024-07-22 17:51 UTC, jordanpadams commented on catalog-legacy/src/main/java/gov/nasa/pds/citool/comparator/CatalogComparator.java
> +/*
resolved per https://github.com/NASA-PDS/registry-harvest-legacy/pull/80/commits/438ebcb33d20ceb8fc3cc5f3fc29912d58a13748

2024-07-22 17:51 UTC, jordanpadams commented on catalog-legacy/src/main/java/gov/nasa/pds/citool/comparator/CatalogComparator.java
> +/*
resolved per https://github.com/NASA-PDS/registry-harvest-legacy/commit/438ebcb33d20ceb8fc3cc5f3fc29912d58a13748

2024-07-22 17:52 UTC, jordanpadams commented
thanks for the PR review @nutjob4life !

2024-07-22 18:00 UTC, nutjob4life commented
> thanks for the PR review @nutjob4life !

Happy to help @jordanpadams!

2024-07-23 00:23 UTC, jordanpadams commented
Merging for now. Still need to do some more research to fix the branch testing.

2024-07-23 15:05 UTC, merged